#ifndef __FILTER_USER_COMMON_H__
#define __FILTER_USER_COMMON_H__

#define FILE_DEVICE_FILTER 0x0F59

#define IOCTL_FILTER_GET_BUFFER CTL_CODE(FILE_DEVICE_FILTER, 2049, METHOD_OUT_DIRECT, FILE_READ_ACCESS)     \
#define IOCTL_FILTER_START_FILTERING CTL_CODE(FILE_DEVICE_FILTER, 2050, METHOD_BUFFERED, FILE_READ_ACCESS)  \
#define IOCTL_FILTER_STOP_FILTERING CTL_CODE(FILE_DEVICE_FILTER, 2051, METHOD_BUFFERED, FILE_READ_ACCESS)   \
#define IOCTL_FILTER_PRINT_DEVICES CTL_CODE(FILE_DEVICE_FILTER, 2052, METHOD_BUFFERED, FILE_READ_ACCESS)    \
#define IOCTL_FILTER_SET_DEVICE_FILTER_ENABLED CTL_CODE(FILE_DEVICE_FILTER, 2053, METHOD_BUFFERED, FILE_WRITE_ACCESS)  \
#define IOCTL_FILTER_GET_DEVICE_LIST CTL_CODE(FILE_DEVICE_FILTER, 2054, METHOD_BUFFERED, FILE_READ_ACCESS)  \
#define IOCTL_FILTER_GET_DEBUG_LEVEL CTL_CODE(FILE_DEVICE_FILTER, 2055, METHOD_BUFFERED, FILE_READ_ACCESS)  \
#define IOCTL_FILTER_SET_DEBUG_LEVEL CTL_CODE(FILE_DEVICE_FILTER, 2056, METHOD_BUFFERED, FILE_WRITE_ACCESS) \
#define IOCTL_FILTER_GET_AUTOTRACE CTL_CODE(FILE_DEVICE_FILTER, 2057, METHOD_BUFFERED, FILE_READ_ACCESS)    \
#define IOCTL_FILTER_SET_AUTOTRACE CTL_CODE(FILE_DEVICE_FILTER, 2058,  METHOD_BUFFERED, FILE_WRITE_ACCESS)  \

#pragma pack(1)

typedef struct{
    DWORD DeviceId;
    BOOLEAN FilterEnabled;
} FILTER_FILTER_ENABLED, *PFILTER_FILTER_ENABLED;

typedef enum _REQUEST_TYPE{
    BusDogReadRequest = 0x2000,
    BusDogWriteRequest,
    BusDogDeviceControlRequest,
    BusDogInternalDeviceControlRequest,
    BusDogPnPRequest,
    BusDogMaxRequestType
} FILTER_REQUEST_TYPE;

typedef struct _REQUEST_PARAMS{
    ULONG p1;
    ULONG p2;
    ULONG p3;
    ULONG p4;

} FILTER_REQUEST_PARAMS;

#define FILTER_REQUEST_PARAMS_INIT(x) { \
    (x)->p1 = 0; \
    (x)->p2 = 0; \
    (x)->p3 = 0; \
    (x)->p4 = 0; \
    }

typedef enum _REQUEST_INTERNAL_DEVICE_CONTROL_TYPE{
    BusDogUSBSubmitURB = 0x2000,
    BusDogUSBResetPort
} FILTER_REQUEST_INTERNAL_DEVICE_CONTROL_TYPE;

typedef enum _REQUEST_USB_DIRECTION{
    BusDogUsbIn = 0x0,
    BusDogUsbOut
} FILTER_REQUEST_USB_DIRECTION;

typedef struct{
    LONG sec; 
    LONG usec;
} FILTER_TIMESTAMP;

typedef struct{
    DWORD DeviceId;
    FILTER_REQUEST_TYPE Type;
    FILTER_REQUEST_PARAMS Params;
    FILTER_TIMESTAMP Timestamp;
    size_t BufferSize;
} FILTER_TRACE, *PFILTER_FILTER_TRACE; // Data buffer follows this structure in memory

typedef struct{
    DWORD DeviceId;
    BOOLEAN Enabled;
    size_t PhysicalDeviceObjectNameSize;
} FILTER_DEVICE_ID, *PFILTER_DEVICE_ID; // unicode string follows this structure in memory

typedef struct{
    DWORD DebugLevel;
} FILTER_DEBUG_LEVEL, *PFILTER_DEBUG_LEVEL;

typedef struct{
    BOOLEAN AutoTrace;
} FILTER_AUTOTRACE, *PFILTER_AUTOTRACE;

#define FILTER_DEBUG_INFO  3
#define FILTER_DEBUG_WARN  2
#define FILTER_DEBUG_ERROR 1
#define FILTER_DEBUG_NONE  0

#pragma pack()

#endif

